### ISSUE TITLE
Fix Validation Errors

### ISSUE THREAD

**Issue by AccessiT3ch** [aschall777/booki77#14]
Currently it looks like there is still a few missing/extra closing tags in `index.html`, which need to be resolved. The browser is handling these errors as best it can, which is why things don't look very broken when we load  the page

- [x] Remove the [extra `</i>`](https://github.com/aschall777/booki77/blob/main/index.html#L37) in the search form
- [x] Add second closing `</div>` and closing `</li>` to [the first filter button](https://github.com/aschall777/booki77/blob/main/index.html#L44)
- [x] Add second closing `</div>` between the existing [`</div>` and `</li>`](https://github.com/aschall777/booki77/blob/main/index.html#L47) on [the rest of the filter buttons](https://github.com/aschall777/booki77/blob/main/index.html#L47) (b/c each filter button opens two divs so they each need to close two divs)
- [x] Upload `index.html` to validate with [WC3's HTML validator](https://validator.w3.org/#validate_by_upload) and fix any errors
- [x] Upload `style.css` to validate with [WC3's CSS validator](https://jigsaw.w3.org/css-validator/#validate_by_upload) and fix any errors

**Comment by AccessiT3ch** [comment]
@aschall777 - These are totally normal when we first start writing code, and these are all some of the first things you wrote, so already we can see signs of improvement and growth!

**Comment by aschall777** [comment]
Made validator changes
